In [1]:
import altair as alt
import pandas as pd

In [32]:
cars_data = pd.read_csv("datasets/car_price_data.csv")

In [3]:
cars_data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody',
    y='median(price)'
)

alt.Chart(...)

In [5]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody',
    y='sum(price)'
)

alt.Chart(...)

In [6]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody',
    y='max(price)'
)

alt.Chart(...)

In [9]:
bar_chart = alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody',
    y='median(horsepower):Q'
)
bar_chart

alt.Chart(...)

In [ ]:
# text not bar graph

text = bar_chart.mark_text().encode(
    text='median(horsepower):Q'
)

text

alt.Chart(...)

In [12]:
bar_chart + text

alt.LayerChart(...)

In [13]:
text = bar_chart.mark_text(dy=-5).encode(
    text='median(horsepower):Q'
)

bar_chart + text

alt.LayerChart(...)

In [15]:
bar_chart = alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x=alt.X('carbody', sort='y'),
    y='median(horsepower):Q'
)

bar_chart

alt.Chart(...)

In [ ]:
#Descending

bar_chart = alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x=alt.X('carbody', sort='-y'),
    y='median(horsepower):Q'
)

bar_chart

alt.Chart(...)

Augmenting and Customizing Bar Chart

In [17]:
car_sample = cars_data.head(10)
car_sample

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167

In [ ]:
alt.Chart(car_sample, height=400, width=600).mark_bar().encode(
    x='CarName',
    y='price'
)

alt.Chart(...)

In [ ]:
#Condition for colors -- Where price is less than 18k

alt.Chart(car_sample, height=400, width=600).mark_bar().encode(
    x='CarName',
    y='price',
    color=alt.condition(
        alt.datum.price > 18000,
        alt.value('pink'),
        alt.value('steelblue')
    )
)

alt.Chart(...)

In [ ]:
# Flip the chart
hot_bar_chart = alt.Chart(car_sample, height=400, width=600).mark_bar().encode(
    y='CarName',
    x='price',
    color=alt.condition(
        alt.datum.price > 18000,
        alt.value('pink'),
        alt.value('steelblue')
    )
)

hot_bar_chart

alt.Chart(...)

In [ ]:
#Draw indicator of the mean/average price
rule = alt.Chart(cars_data).mark_rule(color='red').encode(
    x='mean(price):Q'
)

hot_bar_chart + rule

alt.LayerChart(...)

In [25]:
cars_data['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [36]:
cars_data['drivewheel'].unique()

#cars_data['carbody'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [40]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    y='carbody:O',
    x='count():Q',
    column = 'fueltype:O'
)

alt.Chart(...)

In [ ]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    y='carbody:O',
    x='count():Q',
    column = 'fueltype:O',
    color='drivewheel:N'
)

alt.Chart(...)

In [42]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody:O',
    y='count():Q',
    column = 'fueltype:O',
    color='drivewheel:N'
)

alt.Chart(...)

In [ ]:
alt.Chart(cars_data, height=400, width=600).mark_bar().encode(
    x='carbody:O',
    y=alt.Y('count():Q', stack=None),
    column = 'fueltype:O',
    color='drivewheel:N'
)

alt.Chart(...)